/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRecordsRouteImport } from './routes/_authenticated/records'
import { Route as AuthenticatedQuestionnairesRouteImport } from './routes/_authenticated/questionnaires'
import { Route as AuthenticatedPlanRouteImport } from './routes/_authenticated/plan'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedRecordsUploadRouteImport } from './routes/_authenticated/records.upload'
import { Route as AuthenticatedRecordsIdRouteImport } from './routes/_authenticated/records.$id'
import { Route as AuthenticatedQuestionnairesTypeRouteImport } from './routes/_authenticated/questionnaires.$type'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRecordsRoute = AuthenticatedRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuestionnairesRoute =
  AuthenticatedQuestionnairesRouteImport.update({
    id: '/questionnaires',
    path: '/questionnaires',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlanRoute = AuthenticatedPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecordsUploadRoute =
  AuthenticatedRecordsUploadRouteImport.update({
    id: '/upload',
    path: '/upload',
    getParentRoute: () => AuthenticatedRecordsRoute,
  } as any)
const AuthenticatedRecordsIdRoute = AuthenticatedRecordsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedRecordsRoute,
} as any)
const AuthenticatedQuestionnairesTypeRoute =
  AuthenticatedQuestionnairesTypeRouteImport.update({
    id: '/$type',
    path: '/$type',
    getParentRoute: () => AuthenticatedQuestionnairesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/home': typeof AuthenticatedHomeRoute
  '/plan': typeof AuthenticatedPlanRoute
  '/questionnaires': typeof AuthenticatedQuestionnairesRouteWithChildren
  '/records': typeof AuthenticatedRecordsRouteWithChildren
  '/questionnaires/$type': typeof AuthenticatedQuestionnairesTypeRoute
  '/records/$id': typeof AuthenticatedRecordsIdRoute
  '/records/upload': typeof AuthenticatedRecordsUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/home': typeof AuthenticatedHomeRoute
  '/plan': typeof AuthenticatedPlanRoute
  '/questionnaires': typeof AuthenticatedQuestionnairesRouteWithChildren
  '/records': typeof AuthenticatedRecordsRouteWithChildren
  '/questionnaires/$type': typeof AuthenticatedQuestionnairesTypeRoute
  '/records/$id': typeof AuthenticatedRecordsIdRoute
  '/records/upload': typeof AuthenticatedRecordsUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/plan': typeof AuthenticatedPlanRoute
  '/_authenticated/questionnaires': typeof AuthenticatedQuestionnairesRouteWithChildren
  '/_authenticated/records': typeof AuthenticatedRecordsRouteWithChildren
  '/_authenticated/questionnaires/$type': typeof AuthenticatedQuestionnairesTypeRoute
  '/_authenticated/records/$id': typeof AuthenticatedRecordsIdRoute
  '/_authenticated/records/upload': typeof AuthenticatedRecordsUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/home'
    | '/plan'
    | '/questionnaires'
    | '/records'
    | '/questionnaires/$type'
    | '/records/$id'
    | '/records/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/home'
    | '/plan'
    | '/questionnaires'
    | '/records'
    | '/questionnaires/$type'
    | '/records/$id'
    | '/records/upload'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/home'
    | '/_authenticated/plan'
    | '/_authenticated/questionnaires'
    | '/_authenticated/records'
    | '/_authenticated/questionnaires/$type'
    | '/_authenticated/records/$id'
    | '/_authenticated/records/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/records': {
      id: '/_authenticated/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof AuthenticatedRecordsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/questionnaires': {
      id: '/_authenticated/questionnaires'
      path: '/questionnaires'
      fullPath: '/questionnaires'
      preLoaderRoute: typeof AuthenticatedQuestionnairesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plan': {
      id: '/_authenticated/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof AuthenticatedPlanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/records/upload': {
      id: '/_authenticated/records/upload'
      path: '/upload'
      fullPath: '/records/upload'
      preLoaderRoute: typeof AuthenticatedRecordsUploadRouteImport
      parentRoute: typeof AuthenticatedRecordsRoute
    }
    '/_authenticated/records/$id': {
      id: '/_authenticated/records/$id'
      path: '/$id'
      fullPath: '/records/$id'
      preLoaderRoute: typeof AuthenticatedRecordsIdRouteImport
      parentRoute: typeof AuthenticatedRecordsRoute
    }
    '/_authenticated/questionnaires/$type': {
      id: '/_authenticated/questionnaires/$type'
      path: '/$type'
      fullPath: '/questionnaires/$type'
      preLoaderRoute: typeof AuthenticatedQuestionnairesTypeRouteImport
      parentRoute: typeof AuthenticatedQuestionnairesRoute
    }
  }
}

interface AuthenticatedQuestionnairesRouteChildren {
  AuthenticatedQuestionnairesTypeRoute: typeof AuthenticatedQuestionnairesTypeRoute
}

const AuthenticatedQuestionnairesRouteChildren: AuthenticatedQuestionnairesRouteChildren =
  {
    AuthenticatedQuestionnairesTypeRoute: AuthenticatedQuestionnairesTypeRoute,
  }

const AuthenticatedQuestionnairesRouteWithChildren =
  AuthenticatedQuestionnairesRoute._addFileChildren(
    AuthenticatedQuestionnairesRouteChildren,
  )

interface AuthenticatedRecordsRouteChildren {
  AuthenticatedRecordsIdRoute: typeof AuthenticatedRecordsIdRoute
  AuthenticatedRecordsUploadRoute: typeof AuthenticatedRecordsUploadRoute
}

const AuthenticatedRecordsRouteChildren: AuthenticatedRecordsRouteChildren = {
  AuthenticatedRecordsIdRoute: AuthenticatedRecordsIdRoute,
  AuthenticatedRecordsUploadRoute: AuthenticatedRecordsUploadRoute,
}

const AuthenticatedRecordsRouteWithChildren =
  AuthenticatedRecordsRoute._addFileChildren(AuthenticatedRecordsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedPlanRoute: typeof AuthenticatedPlanRoute
  AuthenticatedQuestionnairesRoute: typeof AuthenticatedQuestionnairesRouteWithChildren
  AuthenticatedRecordsRoute: typeof AuthenticatedRecordsRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedPlanRoute: AuthenticatedPlanRoute,
  AuthenticatedQuestionnairesRoute:
    AuthenticatedQuestionnairesRouteWithChildren,
  AuthenticatedRecordsRoute: AuthenticatedRecordsRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
