/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSpecialtyRouteImport } from './routes/_authenticated/specialty'
import { Route as AuthenticatedRemindersRouteImport } from './routes/_authenticated/reminders'
import { Route as AuthenticatedRecordsRouteImport } from './routes/_authenticated/records'
import { Route as AuthenticatedQuestionnairesRouteImport } from './routes/_authenticated/questionnaires'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPlanRouteImport } from './routes/_authenticated/plan'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedArchiveRouteImport } from './routes/_authenticated/archive'
import { Route as AuthenticatedSpecialtyScvdRouteImport } from './routes/_authenticated/specialty.scvd'
import { Route as AuthenticatedSpecialtyPlaqueRouteImport } from './routes/_authenticated/specialty.plaque'
import { Route as AuthenticatedRecordsUploadRouteImport } from './routes/_authenticated/records.upload'
import { Route as AuthenticatedRecordsIdRouteImport } from './routes/_authenticated/records.$id'
import { Route as AuthenticatedQuestionnairesTypeRouteImport } from './routes/_authenticated/questionnaires.$type'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSpecialtyRoute = AuthenticatedSpecialtyRouteImport.update({
  id: '/specialty',
  path: '/specialty',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRemindersRoute = AuthenticatedRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecordsRoute = AuthenticatedRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuestionnairesRoute =
  AuthenticatedQuestionnairesRouteImport.update({
    id: '/questionnaires',
    path: '/questionnaires',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanRoute = AuthenticatedPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedArchiveRoute = AuthenticatedArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSpecialtyScvdRoute =
  AuthenticatedSpecialtyScvdRouteImport.update({
    id: '/scvd',
    path: '/scvd',
    getParentRoute: () => AuthenticatedSpecialtyRoute,
  } as any)
const AuthenticatedSpecialtyPlaqueRoute =
  AuthenticatedSpecialtyPlaqueRouteImport.update({
    id: '/plaque',
    path: '/plaque',
    getParentRoute: () => AuthenticatedSpecialtyRoute,
  } as any)
const AuthenticatedRecordsUploadRoute =
  AuthenticatedRecordsUploadRouteImport.update({
    id: '/upload',
    path: '/upload',
    getParentRoute: () => AuthenticatedRecordsRoute,
  } as any)
const AuthenticatedRecordsIdRoute = AuthenticatedRecordsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedRecordsRoute,
} as any)
const AuthenticatedQuestionnairesTypeRoute =
  AuthenticatedQuestionnairesTypeRouteImport.update({
    id: '/$type',
    path: '/$type',
    getParentRoute: () => AuthenticatedQuestionnairesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/archive': typeof AuthenticatedArchiveRoute
  '/home': typeof AuthenticatedHomeRoute
  '/plan': typeof AuthenticatedPlanRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/questionnaires': typeof AuthenticatedQuestionnairesRouteWithChildren
  '/records': typeof AuthenticatedRecordsRouteWithChildren
  '/reminders': typeof AuthenticatedRemindersRoute
  '/specialty': typeof AuthenticatedSpecialtyRouteWithChildren
  '/questionnaires/$type': typeof AuthenticatedQuestionnairesTypeRoute
  '/records/$id': typeof AuthenticatedRecordsIdRoute
  '/records/upload': typeof AuthenticatedRecordsUploadRoute
  '/specialty/plaque': typeof AuthenticatedSpecialtyPlaqueRoute
  '/specialty/scvd': typeof AuthenticatedSpecialtyScvdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/archive': typeof AuthenticatedArchiveRoute
  '/home': typeof AuthenticatedHomeRoute
  '/plan': typeof AuthenticatedPlanRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/questionnaires': typeof AuthenticatedQuestionnairesRouteWithChildren
  '/records': typeof AuthenticatedRecordsRouteWithChildren
  '/reminders': typeof AuthenticatedRemindersRoute
  '/specialty': typeof AuthenticatedSpecialtyRouteWithChildren
  '/questionnaires/$type': typeof AuthenticatedQuestionnairesTypeRoute
  '/records/$id': typeof AuthenticatedRecordsIdRoute
  '/records/upload': typeof AuthenticatedRecordsUploadRoute
  '/specialty/plaque': typeof AuthenticatedSpecialtyPlaqueRoute
  '/specialty/scvd': typeof AuthenticatedSpecialtyScvdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/archive': typeof AuthenticatedArchiveRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/plan': typeof AuthenticatedPlanRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/questionnaires': typeof AuthenticatedQuestionnairesRouteWithChildren
  '/_authenticated/records': typeof AuthenticatedRecordsRouteWithChildren
  '/_authenticated/reminders': typeof AuthenticatedRemindersRoute
  '/_authenticated/specialty': typeof AuthenticatedSpecialtyRouteWithChildren
  '/_authenticated/questionnaires/$type': typeof AuthenticatedQuestionnairesTypeRoute
  '/_authenticated/records/$id': typeof AuthenticatedRecordsIdRoute
  '/_authenticated/records/upload': typeof AuthenticatedRecordsUploadRoute
  '/_authenticated/specialty/plaque': typeof AuthenticatedSpecialtyPlaqueRoute
  '/_authenticated/specialty/scvd': typeof AuthenticatedSpecialtyScvdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/archive'
    | '/home'
    | '/plan'
    | '/profile'
    | '/questionnaires'
    | '/records'
    | '/reminders'
    | '/specialty'
    | '/questionnaires/$type'
    | '/records/$id'
    | '/records/upload'
    | '/specialty/plaque'
    | '/specialty/scvd'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/archive'
    | '/home'
    | '/plan'
    | '/profile'
    | '/questionnaires'
    | '/records'
    | '/reminders'
    | '/specialty'
    | '/questionnaires/$type'
    | '/records/$id'
    | '/records/upload'
    | '/specialty/plaque'
    | '/specialty/scvd'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/archive'
    | '/_authenticated/home'
    | '/_authenticated/plan'
    | '/_authenticated/profile'
    | '/_authenticated/questionnaires'
    | '/_authenticated/records'
    | '/_authenticated/reminders'
    | '/_authenticated/specialty'
    | '/_authenticated/questionnaires/$type'
    | '/_authenticated/records/$id'
    | '/_authenticated/records/upload'
    | '/_authenticated/specialty/plaque'
    | '/_authenticated/specialty/scvd'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/specialty': {
      id: '/_authenticated/specialty'
      path: '/specialty'
      fullPath: '/specialty'
      preLoaderRoute: typeof AuthenticatedSpecialtyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reminders': {
      id: '/_authenticated/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof AuthenticatedRemindersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/records': {
      id: '/_authenticated/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof AuthenticatedRecordsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/questionnaires': {
      id: '/_authenticated/questionnaires'
      path: '/questionnaires'
      fullPath: '/questionnaires'
      preLoaderRoute: typeof AuthenticatedQuestionnairesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plan': {
      id: '/_authenticated/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof AuthenticatedPlanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/archive': {
      id: '/_authenticated/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof AuthenticatedArchiveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/specialty/scvd': {
      id: '/_authenticated/specialty/scvd'
      path: '/scvd'
      fullPath: '/specialty/scvd'
      preLoaderRoute: typeof AuthenticatedSpecialtyScvdRouteImport
      parentRoute: typeof AuthenticatedSpecialtyRoute
    }
    '/_authenticated/specialty/plaque': {
      id: '/_authenticated/specialty/plaque'
      path: '/plaque'
      fullPath: '/specialty/plaque'
      preLoaderRoute: typeof AuthenticatedSpecialtyPlaqueRouteImport
      parentRoute: typeof AuthenticatedSpecialtyRoute
    }
    '/_authenticated/records/upload': {
      id: '/_authenticated/records/upload'
      path: '/upload'
      fullPath: '/records/upload'
      preLoaderRoute: typeof AuthenticatedRecordsUploadRouteImport
      parentRoute: typeof AuthenticatedRecordsRoute
    }
    '/_authenticated/records/$id': {
      id: '/_authenticated/records/$id'
      path: '/$id'
      fullPath: '/records/$id'
      preLoaderRoute: typeof AuthenticatedRecordsIdRouteImport
      parentRoute: typeof AuthenticatedRecordsRoute
    }
    '/_authenticated/questionnaires/$type': {
      id: '/_authenticated/questionnaires/$type'
      path: '/$type'
      fullPath: '/questionnaires/$type'
      preLoaderRoute: typeof AuthenticatedQuestionnairesTypeRouteImport
      parentRoute: typeof AuthenticatedQuestionnairesRoute
    }
  }
}

interface AuthenticatedQuestionnairesRouteChildren {
  AuthenticatedQuestionnairesTypeRoute: typeof AuthenticatedQuestionnairesTypeRoute
}

const AuthenticatedQuestionnairesRouteChildren: AuthenticatedQuestionnairesRouteChildren =
  {
    AuthenticatedQuestionnairesTypeRoute: AuthenticatedQuestionnairesTypeRoute,
  }

const AuthenticatedQuestionnairesRouteWithChildren =
  AuthenticatedQuestionnairesRoute._addFileChildren(
    AuthenticatedQuestionnairesRouteChildren,
  )

interface AuthenticatedRecordsRouteChildren {
  AuthenticatedRecordsIdRoute: typeof AuthenticatedRecordsIdRoute
  AuthenticatedRecordsUploadRoute: typeof AuthenticatedRecordsUploadRoute
}

const AuthenticatedRecordsRouteChildren: AuthenticatedRecordsRouteChildren = {
  AuthenticatedRecordsIdRoute: AuthenticatedRecordsIdRoute,
  AuthenticatedRecordsUploadRoute: AuthenticatedRecordsUploadRoute,
}

const AuthenticatedRecordsRouteWithChildren =
  AuthenticatedRecordsRoute._addFileChildren(AuthenticatedRecordsRouteChildren)

interface AuthenticatedSpecialtyRouteChildren {
  AuthenticatedSpecialtyPlaqueRoute: typeof AuthenticatedSpecialtyPlaqueRoute
  AuthenticatedSpecialtyScvdRoute: typeof AuthenticatedSpecialtyScvdRoute
}

const AuthenticatedSpecialtyRouteChildren: AuthenticatedSpecialtyRouteChildren =
  {
    AuthenticatedSpecialtyPlaqueRoute: AuthenticatedSpecialtyPlaqueRoute,
    AuthenticatedSpecialtyScvdRoute: AuthenticatedSpecialtyScvdRoute,
  }

const AuthenticatedSpecialtyRouteWithChildren =
  AuthenticatedSpecialtyRoute._addFileChildren(
    AuthenticatedSpecialtyRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedArchiveRoute: typeof AuthenticatedArchiveRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedPlanRoute: typeof AuthenticatedPlanRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedQuestionnairesRoute: typeof AuthenticatedQuestionnairesRouteWithChildren
  AuthenticatedRecordsRoute: typeof AuthenticatedRecordsRouteWithChildren
  AuthenticatedRemindersRoute: typeof AuthenticatedRemindersRoute
  AuthenticatedSpecialtyRoute: typeof AuthenticatedSpecialtyRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedArchiveRoute: AuthenticatedArchiveRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedPlanRoute: AuthenticatedPlanRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedQuestionnairesRoute:
    AuthenticatedQuestionnairesRouteWithChildren,
  AuthenticatedRecordsRoute: AuthenticatedRecordsRouteWithChildren,
  AuthenticatedRemindersRoute: AuthenticatedRemindersRoute,
  AuthenticatedSpecialtyRoute: AuthenticatedSpecialtyRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
